### ISSUE TITLE
improve performance for group page

### ISSUE THREAD

**Issue by data-doge** [cobudget/cobudget-api#142]
![screen shot 2016-04-21 at 1 24 31 pm](https://cloud.githubusercontent.com/assets/7520103/14723153/6f9983b0-07c4-11e6-98b5-f5e9e9993d3d.png)

42 seconds is too long for the group page to load

**Comment by Connoropolous** [comment]
I've been wondering about that a bit too...

In metamaps, we bootstrap the inclusion of the models into the page, but we
can do that because we're using .erb which are ruby templates, and not
everything has to happen over the API...
https://github.com/metamaps/metamaps/blob/develop/app/views/maps/show.html.erb

On Thu, Apr 21, 2016 at 4:25 PM, Eugene Lynch <notifications@github.com>
wrote:

> [image: screen shot 2016-04-21 at 1 24 31 pm]
> <https://cloud.githubusercontent.com/assets/7520103/14723153/6f9983b0-07c4-11e6-98b5-f5e9e9993d3d.png>
>
> 42 seconds is too long for the group page to load
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cobudget/cobudget-api/issues/142>
>



-- 
Connor Turland
~to craft a sustainable and thriving culture within and without myself~
co-creator of Metamaps.cc

**Comment by kiesia** [comment]
I've made a pull request that will help with this: #146 There's likely couple more refactorings to make.

**Comment by kiesia** [comment]
MembershipsController#index is also a problem, I'll take a look at that too.

**Comment by kiesia** [comment]
Just looking at the responses in the slow queries, they are all hitting the group serializer. So let's get #146 merged in and then look if there are further optimisations to make.

**Comment by kiesia** [comment]
@data-doge @gardner can we close this?
